const SUPA='https://qjvopzschqukitvudgfz.supabase.co';
const KEY='sb_publishable_fDsruYO5WHEqKVRjNEl9Rg_dYpSMrYg';
const AUTH='/auth/v1';
const APP_URL='https://mounirakarkach04-pixel.github.io/piga-pocket-interface-mesh-preview/nadia/';
const DATA_KEY='nadias-app-pages-v5';
const SESSION_KEY='nadia-session-pages-v2';
let session=null;
let data={profile:{name:'Nadia'},events:[],tasks:[],shop:[],notes:[],family:[],routines:[]};
let photos=[];
let slideIndex=0;
let slideTimer=null;
let installPrompt=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function proof(stage){fetch(`${SUPA}/functions/v1/nadia-render-e2e?beacon=${encodeURIComponent(`GH_NADIA_V5_${stage}_${Date.now()}`)}`,{mode:'no-cors',cache:'no-store'}).catch(()=>{});}
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200);}
function userKey(){return `${DATA_KEY}-${session?.user?.id||'guest'}`;}
function authUrl(path){return `${SUPA}${AUTH}${path}`;}
async function authFetch(path,opt={}){return fetch(authUrl(path),{...opt,headers:{apikey:KEY,'Content-Type':'application/json',...(opt.headers||{})}});}
async function jsonSafe(r){try{return await r.json();}catch{return null;}}
function authErrorMessage(j,fallback='Das hat nicht geklappt. Bitte erneut versuchen.'){const code=j?.error_code||j?.code||'';if(code==='email_not_confirmed')return 'Bitte zuerst die Bestätigungs-E-Mail öffnen und die E-Mail-Adresse bestätigen.';if(code==='invalid_credentials')return 'E-Mail-Adresse oder Passwort ist nicht korrekt.';if(code==='user_already_exists'||code==='email_exists')return 'Für diese E-Mail-Adresse besteht bereits ein Konto. Bitte anmelden.';if(code==='over_email_send_rate_limit')return 'Zu viele E-Mails in kurzer Zeit. Bitte kurz warten und erneut versuchen.';return j?.msg||j?.message||j?.error_description||fallback;}
function mountAuth(){const host=$('login');if(!host)return;host.innerHTML=`<div class="loginCard"><div class="loginLogo"><strong>N</strong></div><h1>Nadias App</h1><p>Familie & Alltag, schön organisiert. Sicher mit E-Mail und Passwort.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0 14px"><button id="tabLogin" class="btn rose" type="button" onclick="showAuthMode('login')">Anmelden</button><button id="tabRegister" class="btn ghost" type="button" onclick="showAuthMode('register')">Registrieren</button></div><div id="loginPane" class="authStep"><label class="label" for="loginEmail">E-Mail-Adresse</label><input id="loginEmail" type="email" autocomplete="email" placeholder="name@example.com"><label class="label" for="loginPassword">Passwort</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="Passwort"><button class="btn rose" type="button" onclick="loginAccount()">Anmelden</button><button class="btn ghost" type="button" onclick="resendConfirmation()">Bestätigungs-E-Mail erneut senden</button></div><div id="registerPane" class="authStep hidden"><label class="label" for="registerEmail">E-Mail-Adresse</label><input id="registerEmail" type="email" autocomplete="email" placeholder="name@example.com"><label class="label" for="registerPassword">Passwort</label><input id="registerPassword" type="password" autocomplete="new-password" placeholder="Mindestens 8 Zeichen"><label class="label" for="registerPassword2">Passwort wiederholen</label><input id="registerPassword2" type="password" autocomplete="new-password" placeholder="Passwort wiederholen"><button class="btn rose" type="button" onclick="registerAccount()">Konto erstellen</button><div class="privacy">Danach kommt eine Bestätigungs-E-Mail. Ein Klick auf den Bestätigungslink aktiviert das Konto.</div></div><div id="authMsg" class="notice">Noch kein Konto? „Registrieren“ wählen. Bereits registriert? Einfach anmelden.</div></div>`;}
function showAuthMode(mode){const reg=mode==='register';$('loginPane')?.classList.toggle('hidden',reg);$('registerPane')?.classList.toggle('hidden',!reg);$('tabLogin')?.classList.toggle('rose',!reg);$('tabLogin')?.classList.toggle('ghost',reg);$('tabRegister')?.classList.toggle('rose',reg);$('tabRegister')?.classList.toggle('ghost',!reg);authMsg(reg?'E-Mail und ein eigenes Passwort festlegen.':'Mit E-Mail-Adresse und Passwort anmelden.');}
function authMsg(t,c=''){const m=$('authMsg');if(!m)return;m.textContent=t;m.className=`notice ${c}`;}
async function registerAccount(){const email=$('registerEmail')?.value.trim().toLowerCase()||'';const password=$('registerPassword')?.value||'';const password2=$('registerPassword2')?.value||'';if(!/^\S+@\S+\.\S+$/.test(email))return authMsg('Bitte eine gültige E-Mail-Adresse eingeben.','err');if(password.length<8)return authMsg('Das Passwort muss mindestens 8 Zeichen haben.','err');if(password!==password2)return authMsg('Die beiden Passwörter stimmen nicht überein.','err');authMsg('Konto wird erstellt …');const r=await authFetch(`/signup?redirect_to=${encodeURIComponent(APP_URL)}`,{method:'POST',body:JSON.stringify({email,password})});const j=await jsonSafe(r);if(!r.ok)return authMsg(authErrorMessage(j,'Registrierung fehlgeschlagen.'),'err');localStorage.setItem('nadia-last-email',email);showAuthMode('login');const le=$('loginEmail');if(le)le.value=email;authMsg('Konto angelegt. Bitte jetzt die Bestätigungs-E-Mail öffnen und den Link „E-Mail bestätigen“ antippen. Danach hier mit E-Mail und Passwort anmelden.','ok');proof('REGISTER_OK');}
async function loginAccount(){const email=$('loginEmail')?.value.trim().toLowerCase()||'';const password=$('loginPassword')?.value||'';if(!email||!password)return authMsg('Bitte E-Mail-Adresse und Passwort eingeben.','err');authMsg('Anmeldung läuft …');const r=await authFetch('/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const j=await jsonSafe(r);if(!r.ok||!j?.access_token)return authMsg(authErrorMessage(j,'Anmeldung fehlgeschlagen.'),'err');session=j;localStorage.setItem(SESSION_KEY,JSON.stringify(j));startApp();proof('PASSWORD_LOGIN_OK');}
async function resendConfirmation(){const email=($('loginEmail')?.value||localStorage.getItem('nadia-last-email')||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return authMsg('Bitte zuerst die E-Mail-Adresse eingeben.','err');const r=await authFetch(`/resend?redirect_to=${encodeURIComponent(APP_URL)}`,{method:'POST',body:JSON.stringify({type:'signup',email})});const j=await jsonSafe(r);if(!r.ok)return authMsg(authErrorMessage(j,'Bestätigungs-E-Mail konnte nicht gesendet werden.'),'err');authMsg('Bestätigungs-E-Mail wurde erneut gesendet. Bitte den Link darin antippen.','ok');}
async function sessionFromAuthRedirect(){try{const h=new URLSearchParams(location.hash.slice(1));const access=h.get('access_token');const refresh=h.get('refresh_token');if(!access)return false;const r=await fetch(authUrl('/user'),{headers:{apikey:KEY,Authorization:`Bearer ${access}`}});if(!r.ok)return false;session={access_token:access,refresh_token:refresh||'',token_type:'bearer',user:await r.json()};localStorage.setItem(SESSION_KEY,JSON.stringify(session));history.replaceState(null,'',location.pathname);return true;}catch{return false;}}
async function restoreSession(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(!s?.access_token)return false;const r=await fetch(authUrl('/user'),{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok){localStorage.removeItem(SESSION_KEY);return false;}session={...s,user:await r.json()};return true;}catch{return false;}}
function logout(){localStorage.removeItem(SESSION_KEY);session=null;location.reload();}
function loadData(){try{data={...data,...(JSON.parse(localStorage.getItem(userKey())||'null')||{})};}catch{}render();}
function save(){localStorage.setItem(userKey(),JSON.stringify(data));render();}
function startApp(){$('login')?.classList.add('hidden');$('app')?.classList.remove('hidden');if($('userChip'))$('userChip').textContent=session?.user?.email||'Nadia';if($('settingsEmail'))$('settingsEmail').textContent=session?.user?.email||'';loadData();loadPhotos();detectInstall();proof('APP_START');}
function go(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(id)?.classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));if(b)b.classList.add('on');scrollTo(0,0);id==='gallery'?startSlides():stopSlides();}
function sub(id,b){document.querySelectorAll('.sub').forEach(x=>x.classList.remove('on'));$(id)?.classList.add('on');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));if(b)b.classList.add('on');}
function add(type,obj){data[type].push({id:Date.now()+Math.random(),...obj});save();}
function del(type,id){if(confirm('Eintrag löschen?')){data[type]=data[type].filter(x=>x.id!==id);save();}}
function toggle(type,id){const x=data[type].find(v=>v.id===id);if(x){x.done=!x.done;if(type==='routines'&&x.done)x.streak=(x.streak||0)+1;save();}}
function item(type,x,main,small,check=false){return `<div class="item ${x.done?'done':''}">${check?`<input aria-label="Erledigt" type="checkbox" ${x.done?'checked':''} onchange="toggle('${type}',${x.id})">`:'❀'}<div class="grow"><b>${esc(main)}</b><small>${esc(small||'')}</small></div><button class="iconBtn" onclick="del('${type}',${x.id})">×</button></div>`;}
function render(){const h=new Date().getHours();if($('greet'))$('greet').textContent=`${h<11?'Guten Morgen':h<18?'Guten Tag':'Guten Abend'}, ${data.profile.name||'Nadia'}`;if($('today'))$('today').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date());if($('mT'))$('mT').textContent=data.tasks.filter(x=>!x.done).length;if($('mS'))$('mS').textContent=data.shop.filter(x=>!x.done).length;if($('mE'))$('mE').textContent=data.events.length;if($('mN'))$('mN').textContent=data.notes.length;if($('events'))$('events').innerHTML=[...data.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(x=>item('events',x,x.title,[x.date,x.time,x.cat].filter(Boolean).join(' · '))).join('')||'<div class="empty">Noch keine Termine.</div>';if($('tasks'))$('tasks').innerHTML=data.tasks.map(x=>item('tasks',x,x.text,[x.pr,x.who,x.due].filter(Boolean).join(' · '),true)).join('')||'<div class="empty">Alles erledigt.</div>';if($('shop'))$('shop').innerHTML=data.shop.map(x=>item('shop',x,x.text,[x.qty,x.cat].filter(Boolean).join(' · '),true)).join('')||'<div class="empty">Liste leer.</div>';if($('notes'))$('notes').innerHTML=data.notes.map(x=>item('notes',x,x.title,x.body)).join('')||'<div class="empty">Keine Notizen.</div>';if($('family'))$('family').innerHTML=data.family.map(x=>item('family',x,x.name,[x.birth,x.note].filter(Boolean).join(' · '))).join('')||'<div class="empty">Noch keine Familienkarten.</div>';if($('routines'))$('routines').innerHTML=data.routines.map(x=>item('routines',x,x.text,`${x.freq||''} · Serie ${x.streak||0}`,true)).join('')||'<div class="empty">Keine Routinen.</div>';if($('pName'))$('pName').value=data.profile.name||'Nadia';}
async function shareShop(){const t='Einkaufsliste – Nadias App\n'+data.shop.filter(x=>!x.done).map(x=>'• '+x.text+(x.qty?' ('+x.qty+')':'')).join('\n');if(navigator.share)try{return await navigator.share({title:'Nadias App',text:t});}catch{}location.href='mailto:?subject='+encodeURIComponent('Nadias App')+'&body='+encodeURIComponent(t);}
function dl(n,t,y){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([t],{type:y}));a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800);}
function backup(){dl('nadias-app-backup.json',JSON.stringify(data,null,2),'application/json');}
function importBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data={...data,...JSON.parse(String(r.result))};save();toast('Backup importiert');}catch{toast('Backup ungültig');}};r.readAsText(f);}
function exportIcs(){const a=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Nadias App//DE'];data.events.forEach(e=>{const d=(e.date||new Date().toISOString().slice(0,10)).replaceAll('-','');const t=(e.time||'09:00').replace(':','')+'00';a.push('BEGIN:VEVENT','UID:'+e.id+'@nadias-app','DTSTART:'+d+'T'+t,'SUMMARY:'+e.title,'END:VEVENT');});a.push('END:VCALENDAR');dl('nadias-kalender.ics',a.join('\r\n'),'text/calendar');}
function detectInstall(){if($('installHint'))$('installHint').textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?'iPhone/iPad: Safari → Teilen → „Zum Home-Bildschirm“.':'Android: „App installieren“ tippen oder Browser-Menü → „Zum Startbildschirm hinzufügen“.';}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
async function installApp(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}else if($('installHint'))toast($('installHint').textContent);}
function db(){return new Promise((R,J)=>{const q=indexedDB.open('nadias-photos-pages-v1',1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('photos'))q.result.createObjectStore('photos',{keyPath:'id'});};q.onsuccess=()=>R(q.result);q.onerror=()=>J(q.error);});}
async function loadPhotos(){try{const d=await db();photos=await new Promise((R,J)=>{const q=d.transaction('photos').objectStore('photos').getAll();q.onsuccess=()=>R(q.result||[]);q.onerror=()=>J(q.error);});photos=photos.filter(p=>p.userId===session?.user?.id);renderPhotos();}catch{photos=[];renderPhotos();}}
async function addPhotos(e){const fs=[...(e.target.files||[])].filter(f=>f.type.startsWith('image/')).slice(0,25);if(!fs.length)return;const d=await db();const tx=d.transaction('photos','readwrite');for(const f of fs)tx.objectStore('photos').put({id:crypto.randomUUID(),userId:session.user.id,name:f.name,blob:f,fav:false,created:Date.now()});tx.oncomplete=()=>{e.target.value='';loadPhotos();toast(`${fs.length} Foto(s) hinzugefügt`);};}
function photoUrl(p){return URL.createObjectURL(p.blob);}
function renderPhotos(){const g=$('photoGrid');if(!g)return;g.innerHTML='';photos.sort((a,b)=>(b.fav-a.fav)||(b.created-a.created));photos.forEach((p,i)=>{const e=document.createElement('button');e.className='photoTile';e.innerHTML=`<img alt="${esc(p.name)}"><span class="star">${p.fav?'★':'☆'}</span>`;e.querySelector('img').src=photoUrl(p);e.onclick=()=>openViewer(i);g.appendChild(e);});if(!photos.length){if($('slideHero'))$('slideHero').innerHTML='<div class="galleryEmpty">🌸<br><b>Noch keine Fotos</b><br><span class="muted">Nur ausgewählte Bilder werden übernommen.</span></div>';return;}showSlide();}
function showSlide(){if(!photos.length)return;slideIndex=(slideIndex+photos.length)%photos.length;const p=photos[slideIndex];const h=$('slideHero');if(!h)return;h.innerHTML=`<img alt="Familienfoto"><div class="galleryOverlay"><div><b>Familienmomente</b><div style="font-size:11px;opacity:.8">Slideshow alle 9 Sekunden</div></div><button class="btn" onclick="openViewer(${slideIndex})">Öffnen</button></div>`;h.querySelector('img').src=photoUrl(p);}
function startSlides(){stopSlides();showSlide();slideTimer=setInterval(()=>{if(photos.length){slideIndex=(slideIndex+1)%photos.length;showSlide();}},9000);}
function stopSlides(){if(slideTimer)clearInterval(slideTimer);slideTimer=null;}
function openViewer(i){slideIndex=i;const p=photos[i];if(!p)return;if($('viewerImg'))$('viewerImg').src=photoUrl(p);$('viewer')?.classList.remove('hidden');if($('favBtn'))$('favBtn').textContent=p.fav?'★ Favorit':'☆ Favorit';}
function closeViewer(){$('viewer')?.classList.add('hidden');}
async function mutatePhoto(action){const p=photos[slideIndex];if(!p)return;const d=await db();const tx=d.transaction('photos','readwrite');if(action==='delete'){if(!confirm('Foto aus Nadias App löschen?'))return;tx.objectStore('photos').delete(p.id);}else{p.fav=!p.fav;tx.objectStore('photos').put(p);}tx.oncomplete=()=>{closeViewer();loadPhotos();};}
function saveName(){data.profile.name=$('pName')?.value.trim()||'Nadia';save();toast('Name gespeichert');}
document.addEventListener('DOMContentLoaded',async()=>{mountAuth();proof('DOM_READY');if(await sessionFromAuthRedirect()||await restoreSession())startApp();else{$('login')?.classList.remove('hidden');const last=localStorage.getItem('nadia-last-email');if(last&&$('loginEmail'))$('loginEmail').value=last;}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});});
Object.assign(window,{showAuthMode,registerAccount,loginAccount,resendConfirmation,logout,go,sub,add,del,toggle,shareShop,backup,importBackup,exportIcs,installApp,addPhotos,openViewer,closeViewer,mutatePhoto,saveName});